#!/bin/bash

usage() {
	echo "Usage: $0 [--split] [config_file_path]"
	echo "[config_file_path] defaults to \"$(default_config_path)\""
	echo
	echo "	--split		Enable split tunneling using well-known DoIT IP ranges"
}

default_config_path() {
	if [ -z "$XDG_CONFIG_HOME" ]; then
		echo "$HOME/.config/vpn/config"
	else
		echo "$XDG_CONFIG_HOME/vpn/config"
	fi
}

main() {
	local config_file
	local split_tunnel="false"

	if [[ $EUID -ne 0 ]]; then
		echo "This script must be run as root, use sudo \"$0\" instead" 1>&2
		exit 1
	fi

	# Parse input
	if [[ $# -gt 2 ]]; then
		usage
		exit 2
	else
		# Parse arguments
		for arg in "$@"
		do
			if [[ "$arg" == "--split" ]]; then
				split_tunnel="true"
			else
				config_file="$arg"
			fi
		done

		# Use default config file path if unspecified
		config_file=${config_file:-$(default_config_path)}

		# Check for vpn-slice if necessary
		command -v "vpn-slice" >/dev/null 2>&1
		if [[ $? -ne 0 && "$split_tunnel" == "true" ]]; then
			echo "Error: vpn-slice is required for split tunneling, install and try again"
			echo "https://github.com/dlenski/vpn-slice"
			exit 4
		fi
	fi

	# shellcheck source=./config.sample
	source "$config_file"

	if [[ "$split_tunnel" == "true" ]]; then
		# Common DoIT Subnets https://kb.wisc.edu/ns/page.php?id=3988
		subnets=(
			72.33.0.0/16
			144.92.0.0/16
			128.104.0.0/16
			128.105.0.0/16
			146.151.0.0/17
			146.151.128.0/17
			198.133.224.0/24
			198.133.225.0/24
			198.51.254.0/24
		)
		script="vpn-slice --domains-vpn-dns wisc.edu ${subnets[*]}"
	fi

	echo "Press [CTRL+C] to stop.."
	(echo "${password:?}"; echo 1) | openconnect \
		--user="${user:?}" \
		--usergroup=gateway \
		--passwd-on-stdin \
		--prot=gp \
		--csd-wrapper "${hipreport:?}" \
		--script="${script}" \
		uwmadison.vpn.wisc.edu
}

main "$@"
